baseurl = "https://brianmendoza.com/"
title = "Brian Mendoza"
theme = "pulp"
canonifyurls = true
hasCJKLanguage = true
# pygmentsCodefences = true
# pygmentsUseClasses = true
googleAnalytics = "UA-177299399-1"

[blackfriday]
  hrefTargetBlank = true

[markup.goldmark.renderer]
    unsafe = true # Allow user HTML tags

[params]
    author = "Brian Mendoza"
    avatar = "avatar.png"
    favicon = "icon.ico"
    description = """
        Recent graduate from the University of Houston with a B.S. in Computer Science.
        Seeking a Jr Software Engineering position where I can apply my skills and create 
        high quality software solutions with a team. 
    """
    publicationYear = "2020"
    # listPageDateFormat = "January, 2006" # See https://gohugo.io/functions/format/
    # singlePageDateFormat = "January 2, 2006"
    # custom_css = ["/css/custom.css"]
    # custom_js = ["/js/custom.js"]

# Make sure setting a following option for search bar to work
[outputs]
    section = ["JSON", "HTML"]
    term = ["JSON", "HTML"]

[[menu.main]]
    identifier = "blog"
    #name = "Blog" #If display text link, cancel comment out
    pre = "<i class='fa fa-laptop-code fa-lg'></i>" #Choose your favorite font from Font Awesome
    url = "https://leetcode.com/brianmendoza23/"
    weight = 50

[[menu.main]]
    identifier = "linkedin"
    # name = "LinkedIn"
    pre = "<i class='fab fa-linkedin fa-lg'></i>"
    url = "https://linkedin.com/in/brianmendoza23"
    weight = 20

[[menu.main]]
    identifier = "github"
    # name = "GitHub"
    pre = "<i class='fab fa-github fa-lg'></i>"
    url = "https://github.com/brianm0823"
    weight = 30

[[menu.main]]
    identifier = "email"
    # name = "Email"
    pre = "<i class='fa fa-envelope fa-lg'></i>"
    url = "mailto:contact@brianmendoza.com"
    weight = 40

[[menu.main]]
    identifier = "resume"
    #name = "Resume"
    pre = "<i class='fa fa-file-invoice fa-lg'></i>"
    url = "/files/brian_mendoza_resume.pdf"
    weight = 60
